//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.kintoshmalae.SFXEngine.I18N.en {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.kintoshmalae.SFXEngine.I18N.en.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to load an unsupported audio type. Ensure you check the supported types before attempting to load an audio file..
        /// </summary>
        internal static string Audio_AudioFileFactory_LoadAudioFailedType {
            get {
                return ResourceManager.GetString("Audio_AudioFileFactory_LoadAudioFailedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load audio file. Check the file exists and is of a supported type..
        /// </summary>
        internal static string Audio_AudioFileFactory_LoadFileFailed {
            get {
                return ResourceManager.GetString("Audio_AudioFileFactory_LoadFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert audio file channels for output..
        /// </summary>
        internal static string Audio_ChannelConversionFailed {
            get {
                return ResourceManager.GetString("Audio_ChannelConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to duplicate a stream which does not support this operation. Ensure you check the stream using &apos;canDuplicate&apos; before attempting to copy an effect..
        /// </summary>
        internal static string Audio_SoundFX_DupFailed {
            get {
                return ResourceManager.GetString("Audio_SoundFX_DupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A buffer of insufficient size to store the result was passed in to the call to read..
        /// </summary>
        internal static string Audio_SoundFX_IncompleteBuffer {
            get {
                return ResourceManager.GetString("Audio_SoundFX_IncompleteBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required argument was null / missing..
        /// </summary>
        internal static string NullPointer {
            get {
                return ResourceManager.GetString("NullPointer", resourceCulture);
            }
        }
    }
}
